// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calc_visit_cpp
List calc_visit_cpp(NumericVector x, NumericVector y, NumericVector t, NumericVector xgrid, NumericVector ygrid, double dist, double maxt);
RcppExport SEXP _mapvisit_calc_visit_cpp(SEXP xSEXP, SEXP ySEXP, SEXP tSEXP, SEXP xgridSEXP, SEXP ygridSEXP, SEXP distSEXP, SEXP maxtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xgrid(xgridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ygrid(ygridSEXP);
    Rcpp::traits::input_parameter< double >::type dist(distSEXP);
    Rcpp::traits::input_parameter< double >::type maxt(maxtSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_visit_cpp(x, y, t, xgrid, ygrid, dist, maxt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mapvisit_calc_visit_cpp", (DL_FUNC) &_mapvisit_calc_visit_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_mapvisit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
