# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_visit_cpp <- function(x, y, t, xgrid, ygrid, dist, maxt) {
    .Call('_mapvisit_calc_visit_cpp', PACKAGE = 'mapvisit', x, y, t, xgrid, ygrid, dist, maxt)
}

